"""workspaces

Revision ID: 4e158a994bb7
Revises: None
Create Date: 2014-01-22 13:34:10.488910

"""

# revision identifiers, used by Alembic.
revision = '4e158a994bb7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=30), nullable=False),
    sa.Column('password', sa.Unicode(length=256)),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspaces')
    ### end Alembic commands ###
