{% include meta.html %}
{% include header.html %}
<div id="content-wrapper">
  <div class="inner clearfix">
    <section id="main-content">
      {{ content }}
    </section>
  </div>
</div>
{% include footer.html %}
